name: test postman
on:
  repository_dispatch:
    types: create-branch

jobs:
  create_branch:
    runs-on: ubuntu-latest
    outputs:
      test_env: ${{ steps.step1.outputs.test }}
    steps:
      - name: Test env2
        run: |
          export NEW_TAG="new tag"
          echo "NEW_TAG=${NEW_TAG}" >>$GITHUB_ENV
      - name:  Test env
        id: step1
        run: |
          echo "::set-output name=test::${{ env.NEW_TAG }}"
  test_env:
    runs-on: ubuntu-latest
    needs: create_branch
    steps:
      - name: Print env
        run: |
          echo "Test: ${{needs.create_branch.outputs.test_env}}"