name: test postman
on:
  repository_dispatch:
    types: create-branch

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name:  Test env
        run: |
          echo "Test: ${{ github.event.client_payload.test }}"