name: test postman
on:
  repository_dispatch:
    types: create-branch

jobs:
  create_branch:
    runs-on: ubuntu-latest
    outputs:
      test_env: ${{ steps.step1.outputs.test }}
    steps:
      - name: Test env2
        run: |
          export NEW_TAG2='true'
          echo "NEW_TAG2=${NEW_TAG}" >>$GITHUB_ENV
      - name:  Test env
        id: step1
        run: |
          echo "::set-output name=test::${{ env.NEW_TAG2 }}"
#      - name: run docker
#        uses: docker://iradu/create-branch
      - name: Prin docker env
        id: step2
        run: |
          echo "ENV_DOCKER=$ENV_DOCKER"
  test_env:
    runs-on: ubuntu-latest
    needs: create_branch
    steps:
      - name: Print env
        if: needs.create_branch.outputs.test_env == 'true'
        run: |
          echo "Test: ${{needs.create_branch.outputs.test_env}}"